### ISSUE TITLE
object mutation creates a vault client even if there is nothing to mutate

### ISSUE THREAD

**Issue by czenker** [bank-vaults/vault-secrets-webhook#364]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/bank-vaults/vault-secrets-webhook/issues) for an issue that matches the one I want to file, without success.
- [X] I am not looking for support or already pursued the available [support channels](https://bank-vaults.dev/docs/support/) without success.
- [X] I agree to follow the [Code of Conduct](https://bank-vaults.dev/docs/code-of-conduct/).

### Vault Secrets Webhook Version

1.21.1

### Installation Type

Official Helm chart

### Kubernetes Version

1.25

### Kubernetes Distribution/Provisioner

EKS

### Expected Behavior

When enabling [object mutation](https://bank-vaults.dev/docs/mutating-webhook/configuration/#inject-secret-into-resources) for a custom CRD, vault-secrets-webhook should replace secrets in the resources. But it should not require a ServiceAccount and VAULT_ROLE for a resource that does not contain anything that needs replacement.

### Actual Behavior

Vault-secrets-webhook [authenticates with vault before it checks if there is anything to replace](https://github.com/bank-vaults/vault-secrets-webhook/blob/869915e18382ce9bffff465e068a14c07f8f802d/pkg/webhook/object.go#L126) in a custom CRD. This makes it necessary to have a working default role for vault-secrets-webhook in vault that does not have any capabilities.

If this role does not exists, the webhook ends with the following message:

````
could not mutate object: failed to create vault client: timeout [10s] during waiting for Vault token
````

Depending of the webhook configuration this might block a resource from getting onto the cluster for no good reason.

It would be better if there were some checks done if secrets from vault are needed before creating a vault client. This is implemented for [`ConfigMap` mutation](https://github.com/bank-vaults/vault-secrets-webhook/blob/869915e18382ce9bffff465e068a14c07f8f802d/pkg/webhook/configmap.go#L27-L40) and `Secrets`, but not for any custom `CRD`.

**Comment by akijakya** [comment]
Hi @czenker, thanks for reporting this issue!
I think this behavior is for the code to traverse the object searching for secrets to be replaced only once. Could you please try if this issue is fixed by using the `vault.security.banzaicloud.io/mutate` annotation with the value `skip` on CRDs that should not be mutated?
Also if you have a solution in mind, we appreciate any contributions to the project!

**Comment by czenker** [comment]
`vault.security.banzaicloud.io/mutate: skip` prevents this behavior. But adding this to _every_ resource is impractible and unintuitive if you need the replacement only in a few of the resources.

In my opinion, it should behave similar than secret and configmap mutation. The code just does not look to me as if it could easily be copied.

**Comment by csatib02** [comment]
Hey @czenker,

In case of secret and configmap mutation It's very easy to confirm whether the resource needs to be mutated, but that is not the case with object mutation, because we need to search everywhere inside the object and see if we find a vault secret reference.
So basically the verification step would be the same as mutating. So instead of going through the object twice, the Vault client is always created.

If the object should be mutated, then creating the Vault client will obviously not raise an error.
If it shouldn't be mutated, then as @akijakya pointed out, the `vault.security.banzaicloud.io/mutate` annotation should be set on the resource with `skip` value.
