### ISSUE TITLE
[Openshift] Secrets webhook breaks default SCC on 1.15.2

### ISSUE THREAD

**Issue by pbriet** [bank-vaults/vault-secrets-webhook#69]
**Describe the bug**:

On Openshift, after upgrading from 1.15.1 to 1.15.2, the injector stops working correctly because initContainers are rejected by default security context constraint  ("restricted").

**Steps to reproduce the bug**:
Run the webhook 1.15.2 on Openshift 4.X

**Why**

This is introduced by : 
https://github.com/banzaicloud/bank-vaults/pull/1562
https://github.com/banzaicloud/bank-vaults/commit/bd4da3a0397033c2a908ac02897a230812a489d2#diff-32802053da07acef355a6beb95cc5c4494d6d9c77ee709fb9093c7febb4bfc05L51

The init container is now rejected because : 
* It runs with user "0" even with `vault.security.banzaicloud.io/run-as-non-root: "true"`  - which is not tolerated by Openshift default "restricted" SCC
* You cannot explicitely add any capability with Openshift default "restricted" SCC

Not sure what the solution is : 
* Would it be possible to add an annotation that removes completely the security context from the specs?  (would make sense in an Openshift environment, providing secure defaults)
* If so, would the Openshift default capabilities be compatible with the secret webhook requirements? (reminder: it works fine with 1.15.1)
* If not...  this is kinda of problem, because that would require to use a custom SCC for _each project consuming secrets_. Not really an option.

Thanks,

/kind bug

**Comment by sagikazarmark** [comment]
FYI I'm looking at this issue right now. I'll post an update as soon as I have a solution.

**Comment by sagikazarmark** [comment]
Hey folks!

I wanted to provide an update since I made some progress on this issue.

There are actually multiple problems and I haven't uncovered them all (also, I'm having difficulties with running tests on Openshift, but I'm getting there), but there are some issues that are clear at this point:

Firstly, I believe there is some misunderstanding about what the `vault.security.banzaicloud.io/run-as-non-root` annotation does. If you look into the [Dockerfile](https://github.com/bank-vaults/vault-secrets-webhook/blob/main/Dockerfile#L36) you will see that it already runs as a non-root user **normally**. The annotation only sets `runAsNonRoot` in the [security context](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/).

Secondly (and this is why the containers running these security contexts actually ended up as running root), there is a bug in the current security context implementation. There is a second optional annotation called `vault.security.banzaicloud.io/run-as-user`. When the annotation is not set, its value falls back to 0 (due to how default values work in Go). Due to a bug, in the [code](https://github.com/bank-vaults/vault-secrets-webhook/blob/b79ca0b9abdd69ab533138d4f13be625fa87c7b2/pkg/webhook/pod.go#L848-L849) `runAsUser` is set at the moment even when the annotation is not provided, setting the UID...you guessed it right, 0. That combined with `vault.security.banzaicloud.io/run-as-non-root=true` you get the error that all of you experienced.

Fortunately, this is an easy fix.

Another problem related to the security context is the default set of capabilities introduced in [bank-vaults/bank-vaults#1562](https://github.com/bank-vaults/bank-vaults/pull/1562). Although I still have to verify this, but the PR says those capabilities are necessary for Vault Agent templating only. If that is the case, they can probably be removed from the default list of capabilities and added to a vault agent template specific init container.

I'm hoping to provide a PR in the next couple days.

The challenge is testing though to make sure the changes do not introduce any new regressions and that they actually solve the problem. If anyone wants to volunteer and help with testing, that would be great.
